### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by yarodevuci** [TufayelLUS/Facebook-Video-Downloader-Python#1]
Useless format, most links are in this format https://www.facebook.com/share/r/GVwCTNu3GKp4kN3a/

**Comment by TufayelLUS** [comment]
I have updated the code again to allow support for these types of links. Thanks for your concerns.

**Comment by yarodevuci** [comment]
@TufayelLUS https://www.facebook.com/share/v/cf7EmT9oxhfbGevT/ are this link possible to support? or they have to be in other format?

**Comment by TufayelLUS** [comment]
With the new code, it should be supported. But I can see that this is a group video post and has fewer possibilities to work with. Please try and see if it works.

**Comment by yarodevuci** [comment]
Current link that posted fails @TufayelLUS

**Comment by yarodevuci** [comment]
https://www.facebook.com/reel/1005827824587817?fs=e&mibextid=0NULKw&fs=e&s=TIeQ9V @TufayelLUS this one does not work either
FB Video downloaded failed with error: list index out of range

but if like this https://www.facebook.com/share/r/7o47yEbkJncxBVVn/?mibextid=0NULKw works fine.

Same video

**Comment by TufayelLUS** [comment]
I tried with your first link and it seems to work here. I don't know if facebook changes their source code based on different region as it doesn't use their official API but relies on source code of the webpage, therefore it is possible that the source code changes based on region it is being accessed from. Attached is the screenshot:
![image](https://github.com/TufayelLUS/Facebook-Video-Downloader-Python/assets/39314838/b2e22841-aeec-4f42-b4c1-c255736648e5)

**Comment by yarodevuci** [comment]
ah ok, yeah it's strange

**Comment by yarodevuci** [comment]
@TufayelLUS is it the only way to download fb videos via merging audio and video files?

**Comment by TufayelLUS** [comment]
For now, yes. Because they stream the audio and video files separately, so they need to be merged to get the combined output.

**Comment by yarodevuci** [comment]
Just a suggestion to use ffmpeg-python instead of cmd and make calls async. For Ubuntu support

**Comment by TufayelLUS** [comment]
Thanks for the suggestion. I'll try to create a version with that when I get time.

**Comment by yarodevuci** [comment]
> Thanks for the suggestion. I'll try to create a version with that when I get time.

Thanks so much!
